import Head from 'next/head'
import Image from 'next/image'
import { Space_Mono } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {Center, Flex, Box, Text, InputGroup, Input, Spacer, InputLeftElement, SimpleGrid, VStack, Button, GridItem} from '@chakra-ui/react'
import {FaUser} from 'react-icons/fa'
import { useState } from 'react'
const space = Space_Mono({weight:'700', subsets: ['latin'] })

const PercentBox = ({value, handle}) =>{
  return <Box as='button' bg={value == 'Custom'? "brand.paleGreyCyan":"brand.darkCyan"} 
          fontSize={27} textAlign='center' borderRadius={10} py='10px'
          color={value == 'Custom'? "brand.darkGreyCyan":"white"}
          _hover={{bg:"brand.liteGreyCyan", color:"brand.darkCyan"}} 
          onClick={handle}>{value}</Box>
}

export default function Home() {
  const [bill, setBill] = useState(0)
  const [nop, setNop] = useState(0)
  const [tip, setTip] = useState(0)
  const tipAmount = (bill !== 0 && nop !== 0 && tip !== 0)?  (tip * bill / nop).toFixed(2): 0.00;
  const total = (tipAmount !== 0)?  ((parseFloat(bill)+(tip * bill))/nop).toFixed(2) : 0.00;

  function calc(tips){
    setTip(tips);
    console.log()
  }
  function doReset(){
    setBill(0)
    setNop(0)
    setTip(0)
  }
  return (
    <>
      <Head>
        <title>Tip Calculator App</title>
        <meta name="description" content="Generated by Nida Nido" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={space.className} >
        <Box w='100vw' h='100vh' bg='brand.liteGreyCyan'>
          <Center h='25vh' color='brand.darkCyan' letterSpacing={15}>
            <VStack>
              <Box className={space.className}>SPLI</Box>
              <Box>TTER</Box>
            </VStack>
            
          </Center>
          <Flex bg='white' w='1080px' mx='auto' borderRadius={25} p='25px'>
            <Box p='25px' color='brand.darkGreyCyan' w='540px'>
              <Text fontSize={18} >Bill</Text>
              <InputGroup variant='filled' color='brand.greyCyan' mt='15px' 
                     >
                <InputLeftElement 
                  pointerEvents='none'
                  color='brand.greyCyan'
                  children='$'
                  fontSize={24}
                   />
                <Input placeholder='0' fontSize={24} textAlign='right' type='number'  
                _hover={{border:"1px solid", borderColor:"brand.cyan"}} 
                _focus={{border:"1px solid", borderColor:"brand.cyan"}} 
                onChange={(e)=>{setBill(e.target.value)}}
                value={bill}
                />
              </InputGroup>
              <Text fontSize={18} mt={25}>Select Tip %</Text>
              <SimpleGrid columns={3} spacing='10px' color='white'>
                <PercentBox handle={(e) =>{calc(0.05)}} value="5%" />
                <PercentBox handle={(e) =>{calc(0.1)}} value="10%" />
                <PercentBox handle={(e) =>{calc(0.15)}} value="15%" />
                <PercentBox handle={(e) =>{calc(0.25)}} value="25%" />
                <PercentBox handle={(e) =>{calc(0.5)}} value="50%" />
                <Input placeholder='Custom' bg="brand.paleGreyCyan" 
                      fontSize={27} textAlign='center' borderRadius={10} py='10px'
                    color="brand.darkGreyCyan"
                     />
                <PercentBox value="Custom" />
              </SimpleGrid>
              
              <Text mt='40px'>Number of People</Text>
              <InputGroup variant='filled' color='brand.greyCyan' fontSize={24} mt='15px'>
                <InputLeftElement 
                  pointerEvents='none'
                  color='brand.greyCyan'
                  children={<FaUser />}
                  fontSize={24}
                  h='50px'
                   />
                <Input placeholder='0' textAlign='right' fontSize={24} h='50px' 
                      type='number' pattern='[0-9]'
                      _focus={{border:"1px solid", borderColor:"brand.cyan"}} 
                      _hover={{border:"1px solid", borderColor:"brand.cyan"}} 
                      onChange={(e)=>{setNop(e.target.value)}}
                      value={nop}
                 />
              </InputGroup>
            </Box>
            <Flex bg='brand.darkCyan' w='540px' borderRadius={25} p={50} flexDir="column">
              <Flex justifyContent='space-between'>
                <Box>
                  <Text color='white'>Tip Amount</Text>
                  <Text color='brand.greyCyan'>/ person</Text>
                </Box>
                <Text fontSize="45px" lineHeight="45px"  color='brand.cyan'>${tipAmount}</Text>
              </Flex>
              <Flex mt="50px" justifyContent='space-between'>
                <Box>
                  <Text color='white'>Total</Text>
                  <Text color='brand.greyCyan'>/ person</Text>
                </Box>
                <Text fontSize="45px" lineHeight="45px" color='brand.cyan'>${total}</Text>
              </Flex>
              <Spacer />
              <Button color="brand.darkCyan" bg="brand.cyan" 
                    w="100%" fontSize="24px" height="60px"
                    _hover={{bg:"brand.lightGreyCyan"}}
                    onClick={()=>doReset()}>RESET</Button>
            </Flex>
          </Flex>
        </Box>
        
      </main>
    </>
  )
}
